# Site settings
title: Jennify It
email: thisisjennlee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Catch up with what Jenn has been up to.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jennify.github.io" # the base hostname & protocol for your site
twitter_username: idonttwitter
github_username:  jennify

# Build settings
markdown: kramdown
